### ISSUE TITLE
分离项目依赖如File.js到单独的文件

### ISSUE THREAD

**Issue by Jason23347** [NicodeSS/USTB-Course-ICS-Exporter#3]
这样licence声明将和文件一一对应。另外可以考虑使用webpack生成可执行js脚本，以及如果可以使用nodejs进行网站认证，从而脱离浏览器依赖。

**Comment by NicodeSS** [comment]
分离项目依赖会导致JS内部需要写入项目依赖的绝对路径，不利于远程执行本程序
本项目没有脱离浏览器依赖的打算

**Comment by Jason23347** [comment]
> 分离项目依赖会导致JS内部需要写入项目依赖的绝对路径，不利于远程执行本程序

使用import和require都可以使用相对路径。

> 本项目没有脱离浏览器依赖的打算

如果使用webpack，就可以打包成一个体积减小的可执行js文件，同时可以使本项目source code与release分离。

将本项目分离为多个文件可以提高可读性并且便于维护和重构。
