### ISSUE TITLE
Some methods have too many arguments

### ISSUE THREAD

**Issue by Jason23347** [NicodeSS/USTB-Course-ICS-Exporter#5]
Methods like `addEvent` of icsObject have too many arguments, it is not so easy for maintaining.
It is better to pass an object as one parammter like this:
```js
ics = iscFormatter()
var event = {
    ... // an object
}
ics.addEvent(event)
```
I thought this looks more like "OOM" flavored programming.

**Comment by NicodeSS** [comment]
Accepted. Next version will enhance this.
